# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: KRYPTOMONITOR
description: > # this means to ignore newlines until "baseurl:"
  Project Website
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://matteoromiti.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
# redcarpet:
#     extensions: ["with_toc_data"]
kramdown:
  input: GFM
  syntax_highlighter: rouge


# redcarpet:
#   extensions: ["fenced_code_blocks","no_intra_emphasis"]

plugins:
 - jekyll-gist
 - jekyll-paginate
